name: ZAP Baseline Scan

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Baseline Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://latticenepal.com'  # Target web application
          cmd_options: '-a -r zap_report.html' # Generate report as zap_report.html
          allow_issue_writing: false          # Disable issue creation to avoid rate limits

      - name: Verify Report File
        run: |
          if [ ! -f "zap_report.html" ]; then
            echo "Error: zap_report.html not found!"
            exit 1
          fi

      - name: List Files in Directory
        run: ls -l

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap_report.html
