name: ZAP Scan and Publish Report

on:
  push:
    branches:
      - main  
      - master
  workflow_dispatch:  # Trigger workflow manually

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Scan and Publish Report
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://latticenepal.com'
          cmd_options: '-a -r /zap/wrk/report.html'

      - name: Check for Missing Rules File
        if: ${{ failure() }}
        run: |
          echo "Error: .zap/rules.tsv file is missing or inaccessible."
          exit 1

      - name: Upload Report to GitHub Pages Artifact
        if: ${{ success() }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: /zap/wrk/report.html

  deploy:
    needs: zap_scan
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Grant permissions to deploy pages
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
